Capstone Project 1 - Code with Raihan
raihan2bd/code-with-raihan pull request #1
Opened 2022-11-22 17:02 UTC by raihan2bd

# Capstone project 1 💪 
### Hi There, Finally I completed my 1st capstone project by following this given [template](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) and I called it CodeWithRaihan. This project's main theme is an online full-stack web development Bootcamp. Here is a quick preview of my project:

### Live Preview of my project in a desktop browser.
> <p align="center">
> <img width="375" src="https://api.apify.com/v2/key-value-stores/uAnL1Y3lgKKWOC5CA/records/raihan2bd.github.io-scroll_lossy-comp">
</p>

    ### Live Preview of my project in a mobile browser.
> <p align="center"><img width="375" src="https://api.apify.com/v2/key-value-stores/RqThuApZxJUh3KIx7/records/raihan2bd.github.io-scroll_lossy-comp">
> </p>

### A [Loom](https://www.loom.com/share/25da343eaf84432eb9253b73c257bcee) video for more details about this project.

### I made many changes in this pull request but some of them are:

- First of all, I create a new repo and set up linters on it then I push my main branch code on GitHub.
- Then I created a new branch and added one section at a time with responsible code.
- Day 1 I created this project home page and also add a feature tutors section in this project dynamically using javascript.
- Day 2 I created this project about page.
- Then I fixed my linter error and edit the readme file with a live link and also added preview images.

# Last but not least If you want to see my project live on GitHub pages  [click here](https://raihan2bd.github.io/code-with-raihan/)

2022-11-22 17:49 UTC, ichala requested changes
Hi @raihan2bd 
Good job so far! 
👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No Linters errors✔️ 
- Great Design✔️
- Good Readme File✔️

 ## Required Changes ♻️

- [ ] 🛑  As part of the project requirements, kindly re-take the video presentation and talk about a piece of code that you are proud of 🙏 
- [ ] 🛑 **_Check The comments below_**



## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-22 17:49 UTC, ichala commented on about.html
> +  </footer>
- [ ] Please note that the footer background for the **_mobile version_** should be white both in the index and the about page, kindly fix it to match the design guidelines 🙏

2022-11-22 17:49 UTC, ichala commented on index.html
> +      <p class="hero-details">Boost your career joining our highly professional fullstack Bootcamp and start a remote international fulltime job. Through out this Bootcamp your learning path will be
**_kindly fix these design issues in your index.html header to match the design🙏  :_**

- [ ] Kindly Add some space to the left for the whole content
- [ ] Kindly Increase The Size of the small title on top of the main one
- [ ] kindly update the header description style including the size and the background color, border etc ...  to match the design 
- [ ] kindly remove the button in your header and replace it with some information like shown in the design

your design : 
![image](https://user-images.githubusercontent.com/89282221/203381669-b14bd144-ec3e-4a17-a06a-23b7d16ee8f6.png)


required design : 
![image](https://user-images.githubusercontent.com/89282221/203382013-ec4122b1-3411-4a6d-93c1-e875adab95b1.png)

2022-11-22 17:49 UTC, ichala commented on about.html
> +    </section>
**_kindly fix these design issues in your about.html header to match the design🙏  :_**

- [ ] Kindly Increase The Size of the main title to match the design 
- [ ] Kindly adjust the font weight for the email to be bolder so you match the design

your design : 
![image](https://user-images.githubusercontent.com/89282221/203383365-bedb0580-0022-4513-a6f3-7ed63d5e0a76.png)


required design : 
![image](https://user-images.githubusercontent.com/89282221/203383116-8193da57-0d1a-4c4a-a81a-64dde7774a38.png)

2022-11-22 17:49 UTC, ichala commented on about.html
> +    </section>
- [ ] While you did a great job with the past event section and your design looks stunning for the cards, unfortunately following the design guidelines is part of the requirements, it's like a real-life project where you get an guideline where you have to implement it as it is, kindly updates your cards to match the design guidelines 🙏 

**_Your design :_** 
![image](https://user-images.githubusercontent.com/89282221/203384213-af4ec3da-562a-4a1c-9bff-4e6fe6cb1e9c.png)

**_Required Design : _**
![image](https://user-images.githubusercontent.com/89282221/203384326-12479dfb-cd82-4ab5-92f4-dc7157650606.png)

2022-11-22 17:49 UTC, ichala commented on js/app.js
> +  });
- [ ] This piece of code is awesome I'm really impressed 👏 👏 , Great Job and keep rocking 💯

2022-11-23 08:01 UTC, omarsalem7 approved these changes
Hi @raihan2bd 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Great presentation demo 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 08:03 UTC, merged